### ISSUE TITLE
Exception while deserializing response object to CRDT

### ISSUE THREAD

**Issue by pviotti** [SyncFree/antidote_ts_client#2]
It throws the following exception while trying to deserialize a response from the server to a CRDT object:

```
(node:20016) UnhandledPromiseRejectionWarning: Error: unhandled type: 11
    at ConnectionImpl.readResponseToValue (/home/paolo/ws/antidote-fs/node_modules/antidote_ts_client/dist/antidote.js:115:23)
    at CrdtMapValueImpl.toJsObject (/home/paolo/ws/antidote-fs/node_modules/antidote_ts_client/dist/antidote.js:602:38)
    at AntidoteFS.readMd (/home/paolo/ws/antidote-fs/src/antidote-fs.js:856:66)
    at <anonymous>
```

I'm not sure how to relate that javascript stack trace to the typescript code, but my guess is that this switch lacks the case of the `AntidotePB.CRDT_type.RRMAP`
https://github.com/SyncFree/antidote_ts_client/blob/master/src/antidote.ts#L151-L177

**Comment by peterzeller** [comment]
Should be fixed now and published under 0.2.1. 

By the way: you get an UnhandledPromiseRejectionWarning, if you ignore the result of a Promise (as in https://github.com/SyncFree/antidote-fs/blob/c08e5d10cb37f4316bd28879c058c1a05f972898/src/antidote-fs.js#L215). If you use IntelliJ IDEA you get warnings for these.
